services:
  app:
    build: .
    ports:
      - "${PORT:-5001}:5001"
    environment:
      - PORT=5001
      - WORKERS=${WORKERS:-4}
      - TIMEOUT=${TIMEOUT:-120}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=${REDIS_DB:-0}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
